name: Automatic Deploy to AWS Ec2

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Código fuente - Checkout
        uses: actions/checkout@v3

      - name: Desplegar en EC2 vía SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd www/inmob_api 
            git pull origin main
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env 
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env 
            echo "GOOGLE_GEMINI_AI_API_KEY=${{ secrets.GOOGLE_GEMINI_AI_API_KEY }}" >> .env 
            echo "DB_ENDPOINT_ID=${{ secrets.DB_ENDPOINT_ID }}" >> .env 
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env 
            echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env 

            echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm install
            npm run build
            pm2 restart openmcbo_aws_server || pm2 start dist/main.js --name openmcbo_aws_server
